services:
  svc3:
    container_name: ddev-${DDEV_SITENAME}-svc3
    image: ${BASE_IMAGE:-ubuntu:24.04}-${DDEV_SITENAME}-svc3-built
    build:
      dockerfile_inline: |
        ARG BASE_IMAGE="scratch"
        FROM $${BASE_IMAGE}
        RUN echo "I am svc3 (dockerfile_inline)" > /marker.txt
      args:
        BASE_IMAGE: ${BASE_IMAGE:-ubuntu:24.04}
    command: ["sleep", "infinity"]
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
