services:
  svc2:
    container_name: ddev-${DDEV_SITENAME}-svc2
    image: ${BASE_IMAGE:-ubuntu:24.04}-${DDEV_SITENAME}-svc2-built
    build:
      context: svc2
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-ubuntu:24.04}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
