services:
  svc5:
    container_name: ddev-${DDEV_SITENAME}-svc5
    image: issue8832-stage-name-local-tag
    build:
      context: svc5
      dockerfile: Dockerfile
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
